// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yxdtyut.grpc;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yxdtyut.grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  java.util.List<StudentResponse>
      getResponseList();
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  StudentResponse getResponse(int index);
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  int getResponseCount();
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getResponseOrBuilderList();
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  StudentResponseOrBuilder getResponseOrBuilder(
          int index);
}
