// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yxdtyut.grpc;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yxdtyut.grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  java.util.List<com.yxdtyut.grpc.StudentResponse> 
      getResponseList();
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  com.yxdtyut.grpc.StudentResponse getResponse(int index);
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  int getResponseCount();
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  java.util.List<? extends com.yxdtyut.grpc.StudentResponseOrBuilder> 
      getResponseOrBuilderList();
  /**
   * <code>repeated .com.yxdtyut.grpc.StudentResponse response = 1;</code>
   */
  com.yxdtyut.grpc.StudentResponseOrBuilder getResponseOrBuilder(
      int index);
}
