// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yxdtyut.grpc;

public final class StudentProto3 {
  private StudentProto3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yxdtyut_grpc_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yxdtyut_grpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yxdtyut_grpc_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yxdtyut_grpc_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yxdtyut_grpc_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yxdtyut_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yxdtyut_grpc_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yxdtyut_grpc_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yxdtyut_grpc_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yxdtyut_grpc_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yxdtyut_grpc_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yxdtyut_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yxdtyut_grpc_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yxdtyut_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\020com.yxdtyut.grpc\"\035\n\tMyR" +
      "equest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020" +
      "\n\010realname\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n\003ag" +
      "e\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t" +
      "\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"J\n\023StudentRe" +
      "sponseList\0223\n\010response\030\001 \003(\0132!.com.yxdty" +
      "ut.grpc.StudentResponse\"%\n\rStreamRequest" +
      "\022\024\n\014request_info\030\001 \001(\t\"\'\n\016StreamResponse" +
      "\022\025\n\rresponse_info\030\001 \001(\t2\372\002\n\016StudentServi" +
      "ce\022T\n\025getRealnameBuUsername\022\033.com.yxdtyu" +
      "t.grpc.MyRequest\032\034.com.yxdtyut.grpc.MyRe" +
      "sponse\"\000\022Z\n\017GetStudentByAge\022 .com.yxdtyu" +
      "t.grpc.StudentRequest\032!.com.yxdtyut.grpc" +
      ".StudentResponse\"\0000\001\022c\n\024GetStudentListBy" +
      "Ages\022 .com.yxdtyut.grpc.StudentRequest\032%" +
      ".com.yxdtyut.grpc.StudentResponseList\"\000(" +
      "\001\022Q\n\006BiTalk\022\037.com.yxdtyut.grpc.StreamReq" +
      "uest\032 .com.yxdtyut.grpc.StreamResponse\"\000" +
      "(\0010\001B#\n\020com.yxdtyut.grpcB\rStudentProto3P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_yxdtyut_grpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yxdtyut_grpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yxdtyut_grpc_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_yxdtyut_grpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yxdtyut_grpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yxdtyut_grpc_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_yxdtyut_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_yxdtyut_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yxdtyut_grpc_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_yxdtyut_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_yxdtyut_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yxdtyut_grpc_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_yxdtyut_grpc_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_yxdtyut_grpc_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yxdtyut_grpc_StudentResponseList_descriptor,
        new String[] { "Response", });
    internal_static_com_yxdtyut_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_yxdtyut_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yxdtyut_grpc_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_com_yxdtyut_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_yxdtyut_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yxdtyut_grpc_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
